name: botty
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pywin32
  - pip
  - leptonica
  - tesseract=5.1.0
  - pkg-config
  - rapidfuzz=2.15.1
  - pip:
    - pyinstaller==6.6.0
    - opencv-python==4.6.0.66
    - transitions==0.9.0
    - mss==8.0.0
    - numpy==1.23.5
    - mouse==0.7.1
    - keyboard==0.13.5
    - beautifultable==1.1.0
    - pytweening==1.0.4
    - requests==2.31.0
    - coverage==7.4.4
    - pytest==7.4.3
    - pytest-env==1.1.3
    - pytest-pythonpath==0.7.3
    - pytest-mock==3.14.0
    - graphviz==0.20.3
    - psutil==5.9.8
    - cryptography==42.0.5
    - pillow==10.3.0
    - discord.py==1.7.3
    - parse==1.19.1
    - dependencies/tesserocr-2.5.2-cp310-cp310-win_amd64.whl
    - typing_extensions==4.11.0
    - colorama==0.4.6
    - dataclasses-json==0.6.4
    - pyparsing==3.1.2
